spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/airline_db
    username: airline_user
    password: airline_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 1
        max-concurrency: 5
server:
  port: 8080